# Generated by Django 4.0.1 on 2022-02-08 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('cpf_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_notifica', to='cliente.cliente')),
                ('cpf_remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente_notifica', to='cliente.cliente')),
            ],
        ),
    ]
