# Generated by Django 4.0.2 on 2022-02-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_saldo'),
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='cpf_remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remetente_notifica', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='cpf_destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_notifica', to='cliente.cliente'),
        ),
    ]
