# Generated by Django 4.0.1 on 2022-02-08 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id_transf', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantia', models.FloatField()),
                ('data_transf', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('cliente1_cpf_transf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='cliente.cliente')),
                ('cliente2_cpf_transf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='cliente.cliente')),
            ],
        ),
    ]
