# Generated by Django 4.0.2 on 2022-02-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_saldo'),
        ('transferencia', '0002_transferencia_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='cliente_cpf_transf',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='cliente1_cpf_transf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='cliente2_cpf_transf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='cliente.cliente'),
        ),
    ]
