# Generated by Django 4.0.1 on 2022-02-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='cliente_cpf_taxa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_taxa', to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeiro',
            name='qnt_dias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeiro',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
