# Generated by Django 4.0.1 on 2022-02-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_financeiro_cliente_cpf_taxa_financeiro_qnt_dias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='cliente_cpf_taxa',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='qnt_dias',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor',
        ),
    ]
