# Generated by Django 4.0.1 on 2022-02-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0002_deposito_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='saldo',
        ),
    ]
